### ISSUE TITLE
Hardcoding strings to variables might not actually produce smaller gzip output

### ISSUE THREAD

**Issue by xPaw** [malchata/yall.js#11]
From uglifyjs' repo:
> If your code is very hand-optimized concerning var declarations, this lifting variable declarations might actually increase size.

There's absolutely no need to have shortened variable names in source code as the minified code has mangled variables anyway. It will increase readability a lot by having properly named variables (the minified output will still be the same size).

**Comment by malchata** [comment]
I've been thinking on this as well, and I bet you're right. Readability was never a goal of this project, but rather the smallest possible size while retaining functionality.

My experimentation so far is showing that not hardcoding strings to vars is producing a larger file than before (1.24 KB vs 1.09 KB), but I have not experimented with all of the uglifyjs flags yet.

**Comment by xPaw** [comment]
You should also compare minified size of the gzip output, that would produce a more interesting stat.

**Comment by malchata** [comment]
I've made the library more readable. It expanded the size of the file, which I don't like, but perhaps optimizations can be made after the fact.

**Comment by xPaw** [comment]
Good stuff. I'll be testing this lib on my site soon (I currently have some copy pasted code that does the similar job).

**Comment by malchata** [comment]
FWIW, #10 is fixed in this update, so thank you for raising that flag.
