### ISSUE TITLE
Bug: intersection observer entries not being correctly removed, causing some images to not load

### ISSUE THREAD

**Issue by anthonygore** [malchata/yall.js#13]
```
loadImage = function(img){
  ...
  elements.splice(elements.indexOf(img), 1);
},
```

This doesn't work. Firstly, it doesn't remove the observer entry correctly, secondly, if the element is not found i.e. `elements.indexOf(img) === -1`, the splice removes the last element of the array! The result is that some images don't get loaded.

There's an easy fix, I'll put through a PR.

**Comment by malchata** [comment]
I'm _just_ seeing this now, as it must have gotten buried in my notifications. I've noticed this behavior myself, but didn't know exactly where it was failing. I'll test this out and accept your PR once I can verify the fix. Thank you so much, @anthonygore!

**Comment by malchata** [comment]
FWIW, I did need to still track the number of elements in the array so that the lazy loading behavior could be unbound for users of browsers without Intersection Observer support. So I relied on the `filter` method to achieve this, which seems to be more reliable than `splice`.
