### ISSUE TITLE
How do you plan to handle dynamically loaded HTML

### ISSUE THREAD

**Issue by domfarolino** [malchata/yall.js#15]
Under the [Limitations](https://github.com/malchata/yall.js#limitations) section I noticed you mentioned that this library does not work for dynamically injected markup, however the library should support this at some point in the future; I was wondering if you had a plan for implementing this. It seems like using `MutationObserver` is a good idea, as it is widely supported (including back to IE11), and should be able to efficiently listen to DOM mutations. I'm guessing we could observe on `document.body` or something and listen for `childList` mutations, determine if a child has the `.lazy` class, and therefore should *also* be observed?

Maybe we could make `mediaObserver` a variable global to this module, so we could `.observe` future elements that our `MO` detects. Thoughts?

**Comment by malchata** [comment]
Thanks for this, @domfarolino! It's something I've been thinking about. My only gripe with `MutationObserver` is that Opera Mini doesn't support it, and that browser sees reasonably high usage in emerging markets. But the answer to that could be something as simple as making that an opt-in piece of functionality for advanced use cases, which would allow compatibility back to an older version.

I'm considering a full-on rewrite for a second version that isn't so focused on hacks to minimize library size (but is reasonably small). Are you open to having a discussion about this early in April? I need to focus on conferences for the rest of this month, but have been wanting to get back to this and another project of mine.

**Comment by domfarolino** [comment]
Ah, that makes sense. Yeah, I think opt-in would be the best, since even Mutation Events aren't supported on Opera Mini. I'm definitely open to talking about this when you free up; I'm interested in the rewrite!

Btw, what conferences are you focusing on. Good luck with them :)

**Comment by malchata** [comment]
Thanks for the well wishes. :) I've only got two at the back half of this month: CSSConf AU and Perf Matters Conference. CSSConf involves some heavy travel, and is right next to Perf Matters Conf, so basically March 15th on is on the road, minus a couple days. But yes, let's connect on this when I get back and settled in.

Also, I see you're doing work for Google. :) I'm doing some contract tech writing for them, so maybe our paths will cross!

**Comment by domfarolino** [comment]
Oh nice, sounds fun! Excellent, we shall talk soon then.

And yeah, I've been contributing to Chromium + standards a bit. Ah I'm interested in seeing some of the writing if it's been published yet!

**Comment by malchata** [comment]
I've added support for this in the [shadowfax branch](https://github.com/malchata/yall.js/tree/shadowfax). This branch has not been thoroughly tested, so it's a beta at best!

**Comment by malchata** [comment]
This has been added in the [2.0.0 release](https://github.com/malchata/yall.js/releases/tag/2.0.0). Closing.
