### ISSUE TITLE
images class attribute is lost

### ISSUE THREAD

**Issue by xanisu** [malchata/yall.js#18]
Once yall has executed, my images are losing it's **class** property and a width and height attribute is forced to appear.  

That fails with my needs, because I'm using that image class to use it as `object-fit:'cover'` in it's className.

**Comment by malchata** [comment]
Whoop! Yeah, that's a bad bug. Let me look and see what I missed! Should be something simple.

**Comment by malchata** [comment]
So, I wrote a comment at first and thought it was a bug with my script, but it may be your app design. The default class for lazy loading is `lazy`. When images are loaded, the `lazy` class is removed with this line in yall.js:

```javascript
lazyElement.classList.remove(options.lazyClass);
```

I would recommend against styling the `lazy` class, and instead offload that styling to another class. [`classList.remove`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) shouldn't drop the entire `class` attribute, only the specified class.

That said, can you link me to someplace where this code is running so I can see what's happening?

**Comment by malchata** [comment]
For the relevant section, I think this is closer to what you want:

```javascript
newImageElement.decode().then(() => {
  for (let i = 0; i < element.attributes.length; i++) {
    let attrName = element.attributes[i].name;
    let attrValue = element.attributes[i].value;

    if (env.ignoredImgAttributes.indexOf(attrName) === -1) {
      newImageElement.setAttribute(attrName, attrValue);
    }
  }

  element.replaceWith(newImageElement);
});
```

I need to perform more testing, but if this fix works for you, feel free to use it. Just be aware that it has not been widely tested across browsers yet!
