### ISSUE TITLE
Npm scripts does not run on windows

### ISSUE THREAD

**Issue by kalled** [malchata/yall.js#21]
@malchata, are you interested in a pull request?

**Comment by malchata** [comment]
First off, my sincere apologies for not replying sooner. Life is currently throwing a lot at me to do. :)

Secondly, this is not something that's high on my list, for a number of reasons. First of which being that this addresses the developer experience, while the user experience is something I'm more interested in addressing (and am working on some bugs in that realm at the moment).

_That said_, if you have a solution, I'm interested, but acceptance of a PR is subject to these caveats:

1. It can't break the current build process.
2. It should not introduce significantly more packages.

Let me know what you think!
