### ISSUE TITLE
SVGs not loading in OSX & iOS Safari

### ISSUE THREAD

**Issue by stantonl33** [malchata/yall.js#28]
SVG files fail to load in Safari. The Javascript console has this error:

Unhandled Promise Rejection: EncodingError: Invalid image type.
  [N] (anonymous function)
  [N] promiseReactionJob

I made a test on plunker. You can use it to test here: [https://next.plnkr.co/plunk/GJEd9DNdH9xRHzJanfau](url)

Essentially the test loads a .jpg into the src attribute and an svg into the data-src attribute. I pasted the latest yall.js version (2.1.0) into the plunk script file and added jquery 3.1.1 above it.

**Comment by malchata** [comment]
Able to repro in Safari on High Sierra. I'll triage this for now and get to it when I can, but I suspect I know what the culprit is.
