### ISSUE TITLE
Add an onYallLoad callback option?

### ISSUE THREAD

**Issue by komodo-solutions** [malchata/yall.js#31]
Hi - thanks for the useful script. I have a feature suggestion for you.

In my case I am periodically (re)loading elements containing images in the page. Simply adding the lazy class on all images, and then triggering yall works okay but the placeholder image (which in this case is not derived from the desired image) flickers briefly as a result.

My approach to resolving this is to 'remember' which images have been previously seen & not to lazy load those.

Implementing that remembering process simply requires a `callback(imageSrc)` call at the end of the yallLoad function.

That might be generally useful for other elements too? And other users?

Regards,
Gordon

**Comment by malchata** [comment]
Hi, @komodo-solutions.

I can look into this, but am definitely backlogging it for now. In the meantime, would you be interested in providing a minimal-reproducible example of what effect you're seeing? Preferably a Codepen demo or some such thing?

Thanks!

**Comment by malchata** [comment]
Currently planning on version 3, which will include an events system.

**Comment by malchata** [comment]
An events system has been added to version 3 of yall.js. It's installable through `npm` by referencing the `next` tag like so:

```
npm i yall-js@next
```

Or you can grab `yall.min.js` in the `dist` folder of the [version 3 branch](https://github.com/malchata/yall.js/tree/asfaloth). The readme in that branch shows how to use the events system.
