### ISSUE TITLE
Update joi@9.2.0

### ISSUE THREAD

**Issue by ALPIXELMaiki** [malchata/yall.js#35]
Hi,

Thanks for this usefull tool !

When i install yall with yarn, i have the message below : 
`warning yall > joi@9.2.0: This version is no longer maintained. Please upgrade to the latest version.`

Please can you update joi version ?
Thanks

EDIT : Me again :), when i compile with Webpack, i have this messages : 
```
ERROR  Failed to compile with 2 errors                                                                                                                    09:33:28

These dependencies were not found:

* dns in ./node_modules/isemail/lib/index.js
* net in ./node_modules/joi/lib/string.js
```

Are this libraries not installed with yall ?

**Comment by malchata** [comment]
Hi, @ALPIXELMaiki.

I think you have the wrong repo. The `yall` npm package has nothing to do with this repo. I think you want this repo instead: https://github.com/simon-p-r/yall#readme

Marking invalid and closing.
