### ISSUE TITLE
Can div or span be used instead of img?

### ISSUE THREAD

**Issue by galvarez421** [malchata/yall.js#36]
Does this plugin support using a div or span instead of an img tag to lazy load an image? My use case is that I don't want to use a placeholder image and would like to use a generic div or span element to indicate where the lazy-loaded image should render because I don't want to use an img element where it is it not semantically valid to do so.

**Comment by leeoniya** [comment]
>  I don't want to use an img element where it is it not semantically valid to do so.

IMO, it makes perfect semantic sense for an image placeholder to be an `<img>`. otherwise the browser/crawler cant understand that an image is supposed to be there.

**Comment by galvarez421** [comment]
Sorry, I should have been more precise. By "semantically valid", I actually was referring to the src attribute being required for the img element and since I don't necessarily want to use a placeholder image, there would be no value to provide the attribute.

Regarding a browser/crawler not understanding that an image is supposed to be somewhere, I'm not sure I follow. The target (not placeholder) image is actually not part of the document until the JS lazy loads it. I'm not sure I see the value of a src-less img element or img element with src="" in this case.

**Comment by leeoniya** [comment]
> By "semantically valid", I actually was referring to the src attribute being required

ah, "syntactically valid" then

> The target (not placeholder) image is actually not part of the document until the JS lazy loads it. I'm not sure I see the value of a src-less img element or img element with src="" in this case.

if i'm a crawler or browser and i see `<img>` in an html stream, i know that an image is supposed to be there without ambiguity. whether it has an src or if the target of the src is a 404 is orthogonal. if you instead use `<span class="lazy-img" data-src="...">` it is only vaguely obvious to a human what this could mean.

there are other performance-related concerns with replacing DOM elements since this will always cause a reflow/repaint. with a properly-sized `<img>`, even without `src`, there is no extra loading jank introduced.

also, see my related concerns about DOM mutation and SSR-rendered content: https://github.com/malchata/yall.js/issues/33#issuecomment-448039226

**Comment by malchata** [comment]
I see @leeoniya has more or less made my argument for me, but I'll take my own stab at it, too.

I don't see the value of allowing `<span>`s or `<div>`s to be used where an `<img>` element has inherently better readability, SEO, and accessibility traits. HTML fails softly. Though `src` is a required attribute, the lack of an `src` attribute doesn't inhibit browsers from taking advantage of what's best about `<img>`. An `src`-less `<img>` tag still carries many benefits over `<span>` and `<div>`.

Feel free to continue discussion, but I'm closing this issue for now, as I don't intend to implement this feature request.

**Comment by galvarez421** [comment]
Thank you both for the feedback!

I'm still not entirely convinced, but I think that's more due to my not having researched or thought about this type of scenario enough. I think I am seeing it from the angle of "If the element is not actually part of the document yet, it doesn't make sense to use a non-generic placeholder element for it". For example, I see it as analogous to using a p element to hold the place of where a validation error message _might_ eventually appear; in a case like this, I'd think it'd make more sense to inject the p when it is needed or otherwise use HTML to indicate that it should be ignored until it should be shown. Likewise, the target image should certainly be accessible, SEO-friendly, semantic, etc. when it is actually part of the document, but it isn't really part of the document until it's lazy loaded. The alt attribute, I would think, should be added to the img when it's lazy loaded because it doesn't really apply to the img element with a placeholder or empty src.

Anyway, I'll continue to think about it.
