### ISSUE TITLE
"@babel/plugin-proposal-export-default-from" should be a devDependency

### ISSUE THREAD

**Issue by bencripps** [malchata/yall.js#37]
In the [package.json](https://github.com/malchata/yall.js/blob/master/package.json#L450), we list "@babel/plugin-proposal-export-default-from" as a dependency, even though I believe it's only used in development.

We should remove it so future installers don't add this to their dependency graph.

**Comment by leeoniya** [comment]
or https://github.com/malchata/yall.js/pull/34
