### ISSUE TITLE
Transition/FadeIn for elements?

### ISSUE THREAD

**Issue by jessicaelle** [malchata/yall.js#41]
Hello!

Is there a way to create a fade-in transition for lazy loaded images? 

Thanks!

**Comment by malchata** [comment]
Not that I'm aware of. You may be able to set some CSS transitions on the `lazy` class, but I think there's probably pitfalls involved. I'm currently planning on surfacing an events system in version 3, and I think the flexibility it provides would help you achieve this.

**Comment by malchata** [comment]
An events system has been added to version 3 of yall.js. It's installable through `npm` by referencing the `next` tag like so:

```
npm i yall-js@next
```

Or you can grab `yall.min.js` in the `dist` folder of the [version 3 branch](https://github.com/malchata/yall.js/tree/asfaloth). The readme in that branch shows how to use the events system.

**Comment by malchata** [comment]
Hi, @jessicaelle. I just wanted to follow up to give you an example of how you might tackle transition animations using the new events API in version 3 of yall. I'm currently doing a fade-in effect with [on my site](https://jeremy.codes/), and it looks something like this:

```javascript
document.addEventListener("DOMContentLoaded", () => {
  yall({
    events: {
      load: event => {
        if (event.target.nodeName == "IMG" && !event.target.classList.contains("lazy")) {
          event.target.classList.add("yall-loaded");
        }
      }
    }
  });
});
```

The CSS for making the transitions happen looks something like this (I simplified it from my site's approach):

```css
.content-section img {
  transition: 2s opacity ease-out;
  opacity: .25;
}

.content-section img.yall-loaded {
  opacity: 1;
}

```

If you don't want to use CSS for animations, I'm sure you can pass the element (`event.target`) to whatever JavaScript animation library to make stuff happen.

Also, cautionary note: If you decide to use yall.js 3, understand that it is in alpha yet and requires `IntersectionObserver` to be polyfilled for older browsers (but will fail gracefully if you decide not to). You can conditionally polyfill this feature using [polyfill.io](https://polyfill.io/) like so:

```html
<!-- Put me before yall.js! -->
<script src="https://polyfill.io/v2/polyfill.min.js?features=IntersectionObserver"></script>
```

Hope this helps! Check out the version 3 docs at https://github.com/malchata/yall.js/tree/asfaloth

**Comment by benp** [comment]
Hi @malchata, would that code still work with the current version? It seems the .yall-loaded class is not added anymore. Thanks!
