### ISSUE TITLE
Images not loading on safari

### ISSUE THREAD

**Issue by gplatas** [malchata/yall.js#46]
Tested on OSX and IOS, the image actually loads only if browser is resized or scrolled, this is related to issue #20 i think?

https://yall.now.sh

**Comment by gplatas** [comment]
yeah, sorry about that, i just grabbed that example as im experiencing what appears to be the same issue w/ 2.2.2, but can't actually reproduce it outside my env. I'll try to isolate the issue and get back

**Comment by moofawsaw** [comment]
Images that are outside of the viewport on load aren't fetching for me in Safari. I have 2.2.2. If I scroll to the images that aren't fetched and resize the browser, the load in. 
 I am using:
>   document.addEventListener("DOMContentLoaded", function() {
>   yall({
>     observeChanges: true
>   });
> });

**Comment by malchata** [comment]
@gplatas, @moofawsaw, I've attached a test version of 2.2.3 that might fix this bug. Can you let me know if the attached version fixes your issue, and if not, what specific error you're running into and the exact version of Safari? OS details would be good too.

[yall.min.js.zip](https://github.com/malchata/yall.js/files/2942034/yall.min.js.zip)

**Comment by moofawsaw** [comment]
@malchata Still not working with the new fix. Images outside of the initial viewport are only loaded when the window is resized and not on scroll. It is working in Chrome and Firefox. 

Safari Version 12.0.3
Mac OSX Mojave Version 10.14.3

**Comment by malchata** [comment]
These are my exact specs as well, @moofawsaw, and I'm still not having any trouble with the library working in my local test environment. Can you set up a minimal reproducible test repo? Maybe there's a markup pattern/other edge case you're using that I just haven't anticipated.

**Comment by moofawsaw** [comment]
Here is a test site I set up using dynamic content https://boonbay.webflow.io/test-2

**Comment by malchata** [comment]
Hi, @moofawsaw.

Can you pull down the latest version (either through the repo or npm) and let me know if this is fixed for you? 2.3.1 is the latest.

**Comment by leeoniya** [comment]
i tried v2.3.1 on an iPad2 and iPhone SE and did not encounter any issues.

**Comment by malchata** [comment]
Hi, @moofawsaw. In your example, can you point to https://jlwagner.net/ext/yall/yall.min.js instead of the untranspiled/unuglified source on Github? It'll give me a lot more control to troubleshoot this issue.

Thanks!

**Comment by moofawsaw** [comment]
@malchata 

Updated with the link you provided.

**Comment by hmphu** [comment]
I think the problem happens on IOS <= 10.0 and MacOS < 10.11

**Comment by hmphu** [comment]
@moofawsaw  have you tried the newest version 3.3.1? Does this fixed your issue?

**Comment by moofawsaw** [comment]
@hmphu @malchata Can confirm, images are now loading properly in Safari.

**Comment by malchata** [comment]
Word. Closing this, then.

**Comment by theInt** [comment]
Still not working in safari with ios < 12
