### ISSUE TITLE
null is not an object (evaluating 't.tagName')

### ISSUE THREAD

**Issue by z3niths** [malchata/yall.js#47]
```
n(e){if("IMG"===e.tagName){var t=e.parentNode;"PICTURE"===t.tagName&&i(t.querySelectorAll("source")).forEach(function(e){return s(e)}),s(e)}
```

I found a problem since I start using yall.js
It's tracked by my Sentry and most of the issues came from Safari/IOS/Iphone.

![image](https://user-images.githubusercontent.com/16873595/53860460-b7940c00-4013-11e9-863d-73201236e326.png)

**Comment by malchata** [comment]
Hi, thanks for filing this!

Do you have minimal reproducible test repo for this bug? I'm not able to reproduce it on my iPhone with Mobile Safari, or on Safari on macOS. Just because I can't reproduce it doesn't mean a bug doesn't exist, it just hasn't happened in the use-cases I've employed.
