### ISSUE TITLE
If the uncompressed version is used: js errors

### ISSUE THREAD

**Issue by WalterLenk** [malchata/yall.js#48]
When i use the uncompressed Version (yall.js) errors appear in the console. In Internet Explorer 11 and on iPad, lazy loading then does not work.

For example Line 39 causes a mistake, because "...userOptions" it is actually a comment : 

```
  // Default options, merged with user options.
  const options = {
    lazyClass: "lazy",
    lazyBackgroundClass: "lazy-bg",
    lazyBackgroundLoaded: "lazy-bg-loaded",
    throttleTime: 200,
    idlyLoad: false,
    idleLoadTimeout: 100,
    threshold: 200,
    observeChanges: false,
    observeRootSelector: "body",
    mutationObserverOptions: {
      childList: true,
      subtree: true
    },
    ...userOptions
  };
```

(If I want to compress the uncompressed file, errors also appear.)

**Comment by malchata** [comment]
Hi, @WalterLenk. Thanks for filing this.

The uncompressed version of yall.js is not recommended for use in production. It uses some language features present only in ES6. For example, the feature you're referring to on Line 39 is [object spread syntax](https://github.com/tc39/proposal-object-rest-spread), and is not available in all browsers.

For wide compatibility, it's recommended you use `yall.min.js` in the `dist` folder in this repo, or install from NPM and ensure your babel configuration. If you're using the uncompressed source for debugging purposes, you can configure your module bundler to generate a [source map](https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/) for easier client-side debugging.

Hope this helps.

**Comment by WalterLenk** [comment]
Thank you for your explanation.
