### ISSUE TITLE
option to immediately load images if no Intersection Observer detected?

### ISSUE THREAD

**Issue by leeoniya** [malchata/yall.js#51]
hey @malchata ,

i don't really feel like polyfilling Intersection Observer and would prefer to just immediately load everything. is this something you could add?

thanks!

**Comment by leeoniya** [comment]
eh, it's not just IE11. i forgot iOS Safari doesn't have it :(

oh well, might be a good option either way.

**Comment by malchata** [comment]
Seems reasonable to me. I can take a stab at it when I get a sec.

**Comment by hmphu** [comment]
+1 for this. Safari on IOS doesn't have it

**Comment by hmphu** [comment]
@malchata have you had a look to this case. We're really love to have it

**Comment by leeoniya** [comment]
Safari 12.1 finally has Intersection Observer API [1].

Thankfully, Apple is pretty aggressive at nagging/upgrading their users. Here are of our metrics for Safari 12.1 adoption over the past 2 months (usa, e-commerce, home remodeling):

Safari 12.1:

![safari-12 1](https://user-images.githubusercontent.com/43234/57388871-b8b1f880-717e-11e9-8430-dc9ef38f5b4e.png)

Safari < 12.1:

![safari-not-12 1](https://user-images.githubusercontent.com/43234/57388870-b8b1f880-717e-11e9-8981-67555abe49de.png)

certainly there will always be a long tail, but at least it will be minority rather than a majority.

[1] https://developer.apple.com/documentation/safari_release_notes/safari_12_1_release_notes
