### ISSUE TITLE
Only "lazy" class?

### ISSUE THREAD

**Issue by r-moon** [malchata/yall.js#55]
Hello, first, thank you very much for the time you have spent, spend, on yall.

Is there any way to tell yall to observe more than one class?.
I mean default is "lazy", anyway I can add one more.

Scenerio:
Iframes (youtube videos) created in an editor (Quill.js) as part of a post (not wp) and no chance to change classes or add them because it is javascript and when they, iframes, are loaded in page with their own class I have no chance to add "lazy" unless I edit the script, which is far away from my knowledge.

Thank you and all the best!

**Comment by malchata** [comment]
yall doesn't have support to observe more than one class, but that class can be changed with the `lazyClass` option. That may help you a bit, but I have no plans to add support to observe multiple classes in the future.

**Comment by r-moon** [comment]
Thanks for your reply, I do understand.
All the best!

 
> yall doesn't have support to observe more than one class, but that class can be changed with the `lazyClass` option. That may help you a bit, but I have no plans to add support to observe multiple classes in the future.
