### ISSUE TITLE
Lazy Loading Fails With Polyfil 

### ISSUE THREAD

**Issue by radfahrer** [malchata/yall.js#61]
When using the `intersection-observer` polyfill package from NPM, lazy loading doesn't work. The compatibility check here https://github.com/malchata/yall.js/blob/13e7c5cc515986b19672e5af89c79feedee72e95/src/yall.mjs#L88 seems to be failing.

**Comment by radfahrer** [comment]
The polyfill doesn't create the prototype.

**Comment by turboatcrazyfactory** [comment]
We also face the problem in IE with yall version 3.1.2
