### ISSUE TITLE
observeRootSelector not working for list of IDs

### ISSUE THREAD

**Issue by wasshuber** [malchata/yall.js#63]
From the manual of yall.js "... you can confine the observer to any valid CSS selector".
However it doesn't work if I use a list such as "#id1,#id2,#id3,#id4".
It works with a single ID such as "#id1".

**Comment by malchata** [comment]
Cursory research reveals that a single mutation observer can't operate on multiple elements. I'll need to slightly adjust how yall binds the observer(s) to element(s), which will require a slight bit of refactoring. I'll prioritize this above other issues.

**Comment by malchata** [comment]
Hi, @wasshuber. I made some changes to resolve this, but I'd like you to check to see if it serves your purposes before I go ahead and publish a new version. [Here's a link to the new minified build](https://raw.githubusercontent.com/malchata/yall.js/master/dist/yall.min.js). Hope it works!

**Comment by malchata** [comment]
Pinging @wasshuber! Did this new build help fix your issue? If so, I'd like to do a release.
