### ISSUE TITLE
Firefox slider with lazyloading doesnt work

### ISSUE THREAD

**Issue by adhocore** [malchata/yall.js#64]
Firefox version 68 (should happens in other versions as well)
Yall version 3.1.1
jQuery FlexSlider version 2.2.2

Only the first slide is lazy loaded and the rest shows blank or default placeholder always.

We use observer `yall({ observeChanges: true })` with polyfill.

We however noticed that if we scroll down and again scroll up the latest slider in view is loaded (but not all the others)

**Comment by malchata** [comment]
Hi, @adhocore.

Can you provide a minimal test repo for this? Additionally, can you verify if the latest version of yall (3.1.5) fixes this for you?

**Comment by adhocore** [comment]
thanks for this libray.

will check on 3.1.5 and let you know

**Comment by adhocore** [comment]
working fine :100: thanks :+1:
