### ISSUE TITLE
yall doesn't seem to work on iOS

### ISSUE THREAD

**Issue by bracketsberlin** [malchata/yall.js#68]
Hi, 
while testing yall's lazy loading on iOS, we found out, that no image was loaded there at all. I thought maybe it's something with my page setup. However, I create a small JSbin which allows reconstructing the issue outside the original environment.

I only see the placeholder image but the lazy-loaded nature image never appears in iOS:
https://jsbin.com/gexusareze/edit?html,output

I tested it on iOS 9 through Browserstack. Can you please check that issue?

Thank you,
bb

**Comment by malchata** [comment]
Hi,

As per your example, I can see that you have not polyfilled `IntersectionObserver`, which means that yall _will_ fail on iOS 9.

Additionally, I can see that you've included yall.js twice: once as an external resource, and another inlined version.

If you can polyfill `IntersectionObserver`, ensure you're only including one version of yall.js, and determine if there's still an issue, I'm happy to look into this as a bug.

**Comment by bracketsberlin** [comment]
Hi,
oh jeeez. I am sorry, I totally forget about the polyfill. 
I updated the fiddle and it now works as it should: https://jsbin.com/xabapemuya/edit?html,output

Thanks for your hint :-)

**Comment by malchata** [comment]
No worries! And I'm sorry if it wasn't clearer in the documentation. I'm planning on putting a ToC on it to make it easier to navigate. :)
