### ISSUE TITLE
Google Page Speed still asking to defer offscreen images

### ISSUE THREAD

**Issue by Brunzig** [malchata/yall.js#69]
Hi fellas,

I've implemented yall on our company site, i have included the polyfill.io script in the example but google page speed is still telling me to defer off screen images even though they are. 

Any ideas as to why? Every image has the lazy class attached and the data-src URL. I'm baffled.

Thanks

**Comment by Brunzig** [comment]
I've found the issue why it still shows in page speed. If I remove the src and leave data-src it works and passed GPS. Is there a fix for this? I don't want to leave the src blank and have no placeholder...

**Comment by leeoniya** [comment]
GPS is quite outdated, i'm not sure it's even updated anymore. try using the Lighthouse Audits panel in Chrome's devtools.

**Comment by Brunzig** [comment]
> GPS is quite outdated, i'm not sure it's even updated anymore. try using the Lighthouse Audits panel in Chrome's devtools.
> 
> EDIT: sorry, this probably doesnt really address your concern.

Would you suggest keeping the src URL as well as the data-src URL for images?

**Comment by leeoniya** [comment]
here's what i usually do.

for images i know will at least partially be above the fold on all screen sizes, they're non-lazy and i just specify the final src.

all images on my sites have one of several aspect ratios, (eg, 3:2, 1:1, 16:9) for which i have a transparent placeholder png that i set as the src. this has the benefit of only a few additional http requests for tiny files and allows the CSS/layout to be finalized so there's no layout shifting when the final src loads. you can get the same effect with width/height attrs or css, but it's a bit more work.

for example, this 150x100.png is 108 bytes:

![150x100](https://user-images.githubusercontent.com/43234/63366806-22c26800-c340-11e9-911f-4f2b62346eda.png)

**Comment by rkumorek** [comment]
Not sure if it's possible in your stack but you could try inlining placeholder images as base64 encoded images instead of pngs. This would remove unnecessary http requests.

The issue you have will happen with every lazyloading library so it is not an `yall-js` issue per se.
