### ISSUE TITLE
Strange error in the latest 3.1.6 version

### ISSUE THREAD

**Issue by adhocore** [malchata/yall.js#74]
we have thousands of such logs in sentry.
please see the stack trace below:

```
TypeError: e.dataset is not an Object. (evaluating 'c[n]in e.dataset')
  at n(/yall-js/dist/yall.min.js:1:775)
  at b(/yall-js/dist/yall.min.js:1:879)
  at g(/yall-js/dist/yall.min.js:1:950)
  at f(/yall-js/dist/yall.min.js:1:503)
  at m(/yall-js/dist/yall.min.js:1:1077)
  at g(/yall-js/dist/yall.min.js:1:950)
  at ? (/yall-js/dist/yall.min.js:1:1394)
```

is it because of `dataset` attribute missing? does it make sense for the library to make that attribute optional?

i will update here if there are more findings

**Comment by malchata** [comment]
I need more context before I can figure this out.

1. What platform are you using this on?
2. What browser, and what version?
3. Any other info you think might be relevant.

In this case, `dataset` is not an attribute. It's [a web API for managing](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset) `data-` attributes on elements. yall.js uses it to track image sources it should load.

**Comment by malchata** [comment]
Closing this, since I haven't received followup info on this. My guess is that the errors are coming from clients that don't support `dataset`, which would be unsupported anyway. If you want to continue discussion, feel free to continue it here and I'll reopen this issue if need be.
