### ISSUE TITLE
Would you add extensions/libraries facilitating usage of this library?

### ISSUE THREAD

**Issue by adhocore** [malchata/yall.js#78]
I am using `malchata/yall.js` for long time now and it works like a charm. Thank you for this cool stuff.

(I sometimes [run](https://github.com/malchata/yall.js/issues/74) into [issues](https://github.com/malchata/yall.js/issues/64) but that's not a biggie).

I am wondering if you would be kind enough to mention (preferably in README.md) a twig template engine extension that i developed to seamlessly integrate `malchata/yall.js`!

The extension is FOSS available at [adhocore/twig-yall](https://github.com/adhocore/twig-yall)!

If you have certain and clear requirements to add stuffs like this in Integration section somewhere in README please let me know so I can do a PR.

**Comment by malchata** [comment]
Sure! I'd be fine with that. For something this simple, just fork and create a new heading toward the end of the README (or wherever seems acceptable) and make a new PR.
