### ISSUE TITLE
Type error when dataset is undefined.

### ISSUE THREAD

**Issue by radfahrer** [malchata/yall.js#86]
We're seeing some issues in our error reporting "Cannot use 'in' operator to search for 'srcset' in undefined"

It looks like it's happening here: https://github.com/malchata/yall.js/blob/319ceeabe940d93cd072357ce4c199f8346a6f11/src/yall.mjs#L58
I'm guessing that whatever "element" is getting passed in doesn't have a `dataset`. Should be a simple check to add in before trying to flip attributes to check if there is a dataset.

**Comment by verlok** [comment]
Pssst! Check out https://github.com/verlok/lazyload
