### ISSUE TITLE
Yall not working on modal window iframe.

### ISSUE THREAD

**Issue by NickDimou** [malchata/yall.js#89]
I am currently using this amazing script but I am not able to make it work for modal windows (iframe and/or img). I have published a generic question in stackoverflow [here](https://stackoverflow.com/questions/65707707/lazy-load-iframe-only-after-modal-is-triggered?noredirect=1#comment116237923_65707707) .

Can you please assist?

**Comment by malchata** [comment]
Is the modal window markup part of the HTML that is sent by the server? If not, yall.js may not pick it up at the `DOMContentLoaded` event. For cases like these, the [`observeChanges` option](https://github.com/malchata/yall.js#observechanges) might be what you need to get things working.
