### ISSUE TITLE
Implement Intersection Observer

### ISSUE THREAD

**Issue by malchata** [malchata/yall.js#9]
[This article](https://hacks.mozilla.org/2017/08/intersection-observer-comes-to-firefox/) by Dan Callahan alerted me to the existence of Intersection Observer, a browser feature that may give us a better alternative to doing checks with `getBoundingClientRect`.

**Comment by xPaw** [comment]
Am I understanding it correctly that you are creating new IntersectionObserver for each image? Perhaps it would be a lot better to create a single one and observe multiple images in it?

**Comment by malchata** [comment]
Thanks for this question! I had similar thoughts about this, and it was my original intent. However, when I went to feed a collection of elements with `querySelectorAll` into the `observe` method, I always got this TypeError:

<img width="568" alt="screen shot 2017-08-11 at 10 02 13 am" src="https://user-images.githubusercontent.com/1635238/29218955-31a4a906-7e7c-11e7-947e-45d6de533bb5.png">

I would prefer not having to loop through all elements and creating a separate observer for them, but I'm not sure how and if that's possible with IntersectionObserver. I've combed through the API docs, but I'm not getting any ideas. Would you be able to provide some insight? I'm sure I've missed something.

**Comment by xPaw** [comment]
You can have one observer and call `observe` on it for multiple elements, that should do the trick.

**Comment by malchata** [comment]
I didn't think of that! I'll test this out. Thank you so much for your guidance. :)
